### ISSUE TITLE
[BUG]- upgrade talents is not working after class change

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#1050]
foundry.js:659 Error: Failed to initialize Item [SfNyHuaRGBIhU6JR]. ItemEd [SfNyHuaRGBIhU6JR] validation errors:
  system: 
    talentCategory: class is not a valid choice
    at Hooks.onError (foundry.js:658:24)
    at Items._initialize (foundry.js:12152:15)
    at new DocumentCollection (foundry.js:12132:10)
    at new DirectoryCollection (foundry.js:11831:10)
    at new WorldCollection (foundry.js:12448:1)
    at new Items (foundry.js:13834:1)
    at Game.initializeDocuments (foundry.js:9163:30)
    at Game.setupGame (foundry.js:9057:10)
    at async Game._initializeGameView (foundry.js:10435:5)

**Comment by ChristopherSD** [comment]
I need a bit more information to start investigating 😆 
Any steps to reproduce it?

**Comment by patrickmohrmann** [comment]
must have been part of an other issue, not happening any more
