### ISSUE TITLE
Attribute roll not possible

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#596]
**Describe the bug**
attribute rolls throw an error:
```
actor.mjs:152 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'strain')
    at #processRoll (actor.mjs:152:41)
    at ActorEd.rollAttribute (actor.mjs:102:22)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by patrickmohrmann** [comment]
closed with #247
