### ISSUE TITLE
Darkmode setting

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#687]
Darkmode setting error:

foundry.js:3318 Uncaught Error: This is not a registered game setting
    at ClientSettings.get (foundry.js:3318:42)
    at #createContext (foundry-esm.js:50862:36)
    at AudioHelper._onFirstGesture (foundry-esm.js:50838:46)
    at document.addEventListener.once (foundry-esm.js:50493:62)
    at _registerDarkMode (init.mjs:79:23)
    at Object.fn (init.mjs:69:9)
    at #call (foundry.js:608:20)
    at Hooks.callAll (foundry.js:565:17)
    at Game.initialize (foundry.js:8861:11)
    at window.addEventListener.once (foundry.js:95072:26)

**Comment by patrickmohrmann** [comment]
darkmode will be browser specific in the future with AppV2
