### ISSUE TITLE
starting char gen from create Actor throws an error

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#828]
**Describe the bug**
foundry.js:659 Error: An error occurred while rendering CharacterGenerationPrompt 110. game.settings.get(...).map is not a function
    at Hooks.onError (foundry.js:658:24)
    at foundry.js:5798:13

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by patrickmohrmann** [comment]
solved
